import { Deal, LeaderboardEntry } from "./types";

export function createMockDeals(): Deal[] {
  return [
    {
      id: "deal-001",
      name: "Marina Heights Tower - Unit 42B",
      nameAr: "برج مارينا هايتس - الوحدة 42ب",
      city: "Dubai",
      propertyType: "residential",
      tokenizationMode: "fractional",
      totalShares: 100,
      sharePrice: 15000,
      currency: "AED",
      totalValue: 1500000,
      propertyAddress: "Dubai Marina, Tower 7, Unit 42B",
      propertyAddressAr: "دبي مارينا، برج 7، الوحدة 42ب",
      status: "active",
      createdAt: "2025-01-15T10:00:00Z",
      parties: [
        { id: "p1", name: "Ahmed Al Maktoum", role: "seller", sharePercent: 100, kycStatus: "verified", email: "ahmed@example.ae" },
        { id: "p2", name: "Sarah Chen", role: "buyer", sharePercent: 35, kycStatus: "verified", email: "sarah@example.com" },
        { id: "p3", name: "Omar Hassan", role: "buyer", sharePercent: 25, kycStatus: "pending", email: "omar@example.ae" },
        { id: "p4", name: "Dubai Land Brokers", role: "broker", kycStatus: "verified", email: "info@dlb.ae" },
        { id: "p5", name: "Emirates Escrow Services", role: "escrow_agent", kycStatus: "verified", email: "ops@ees.ae" },
      ],
      steps: [
        { id: "s1", title: "KYC/AML Verification", titleAr: "التحقق من الهوية ومكافحة غسيل الأموال", status: "done", requiredDocs: ["kyc_doc", "passport", "emirates_id"], notes: ["All buyer KYC docs submitted"], order: 1, completedAt: "2025-01-20T14:30:00Z" },
        { id: "s2", title: "Title Deed Verification", titleAr: "التحقق من سند الملكية", status: "done", requiredDocs: ["title_deed"], notes: ["Title verified with Dubai Land Department"], order: 2, completedAt: "2025-01-22T09:15:00Z" },
        { id: "s3", title: "NOC Collection", titleAr: "جمع شهادات عدم الممانعة", status: "in_progress", requiredDocs: ["noc"], notes: ["Waiting for developer NOC"], order: 3, blockedReason: "Developer response pending since 3 days" },
        { id: "s4", title: "Property Valuation", titleAr: "تقييم العقار", status: "in_progress", requiredDocs: ["valuation_report"], notes: ["RICS valuation ordered"], order: 4 },
        { id: "s5", title: "Escrow Setup", titleAr: "إعداد حساب الضمان", status: "todo", requiredDocs: ["escrow_agreement"], notes: [], order: 5 },
        { id: "s6", title: "Settlement", titleAr: "التسوية", status: "todo", requiredDocs: ["spa"], notes: [], order: 6 },
        { id: "s7", title: "Token/Share Issuance", titleAr: "إصدار الحصص/الرموز", status: "todo", requiredDocs: [], notes: [], order: 7 },
        { id: "s8", title: "Post-Close Automation", titleAr: "أتمتة ما بعد الإغلاق", status: "todo", requiredDocs: [], notes: [], order: 8 },
      ],
      docs: [
        { id: "d1", type: "passport", filename: "sarah_chen_passport.pdf", uploadedAt: "2025-01-16T10:00:00Z", extractedFields: { full_name: "Sarah Chen", nationality: "Singapore", passport_no: "E1234567A", expiry: "2028-03-15" }, verificationStatus: "verified", uploadedBy: "Sarah Chen" },
        { id: "d2", type: "emirates_id", filename: "omar_hassan_eid.pdf", uploadedAt: "2025-01-17T11:30:00Z", extractedFields: { full_name: "Omar Hassan", id_number: "784-1990-1234567-1", expiry: "2027-06-20" }, verificationStatus: "verified", uploadedBy: "Omar Hassan" },
        { id: "d3", type: "title_deed", filename: "marina_heights_title.pdf", uploadedAt: "2025-01-18T09:00:00Z", extractedFields: { property_id: "DM-42B-7", owner: "Ahmed Al Maktoum", area_sqft: "1,250", plot_no: "JBR-7842" }, verificationStatus: "verified", uploadedBy: "Ahmed Al Maktoum" },
        { id: "d4", type: "kyc_doc", filename: "sarah_chen_kyc_bundle.pdf", uploadedAt: "2025-01-16T10:30:00Z", extractedFields: { risk_level: "Low", source_of_funds: "Employment", pep_status: "No" }, verificationStatus: "verified", uploadedBy: "Sarah Chen" },
      ],
      audit: [
        { ts: "2025-01-15T10:00:00Z", actor: "System", action: "Deal Created", detail: "Marina Heights Tower deal initiated", emoji: "🏡" },
        { ts: "2025-01-16T10:00:00Z", actor: "Sarah Chen", action: "Doc Uploaded", detail: "Passport uploaded for KYC verification", emoji: "📜" },
        { ts: "2025-01-17T11:30:00Z", actor: "Omar Hassan", action: "Doc Uploaded", detail: "Emirates ID uploaded — habibi is ready!", emoji: "🧾" },
        { ts: "2025-01-18T09:00:00Z", actor: "Ahmed Al Maktoum", action: "Doc Uploaded", detail: "Title deed submitted to DLD for verification", emoji: "📜" },
        { ts: "2025-01-20T14:30:00Z", actor: "DeedFlow AI", action: "Step Completed", detail: "KYC/AML checks passed — all clear, yalla!", emoji: "✅" },
        { ts: "2025-01-22T09:15:00Z", actor: "Dubai Land Dept", action: "Step Completed", detail: "Title deed verified — the falcon has landed 🦅", emoji: "✅" },
        { ts: "2025-01-23T08:00:00Z", actor: "DeedFlow AI", action: "NOC Requested", detail: "NOC request sent to Emaar — waiting faster than Friday brunch queue", emoji: "⏳" },
      ],
      fieldReports: [
        { ts: "2025-01-19T15:00:00Z", user: "Dubai Land Brokers", note: "Property inspection completed. Unit in excellent condition. Marina view confirmed.", mood: "positive", lang: "en" },
        { ts: "2025-01-21T10:00:00Z", user: "Omar Hassan", note: "Excited about the investment. Looking forward to completion.", mood: "positive", lang: "en" },
      ],
      metrics: { complianceScore: 68, riskScore: 25, estTimeToCloseDays: 14 },
    },
    {
      id: "deal-002",
      name: "Al Reem Island Commercial Plaza",
      nameAr: "مجمع جزيرة الريم التجاري",
      city: "Abu Dhabi",
      propertyType: "commercial",
      tokenizationMode: "tokenized",
      totalShares: 1000,
      sharePrice: 500,
      currency: "AED",
      totalValue: 500000,
      propertyAddress: "Al Reem Island, Plot C-14, Ground Floor",
      propertyAddressAr: "جزيرة الريم، القطعة C-14، الطابق الأرضي",
      status: "active",
      createdAt: "2025-02-01T08:00:00Z",
      parties: [
        { id: "p6", name: "Fatima Al Nahyan", role: "seller", sharePercent: 100, kycStatus: "verified", email: "fatima@example.ae" },
        { id: "p7", name: "Tech Invest LLC", role: "buyer", sharePercent: 60, kycStatus: "verified", email: "invest@techinvest.ae" },
        { id: "p8", name: "Khalid Al Suwaidi", role: "buyer", sharePercent: 20, kycStatus: "verified", email: "khalid@example.ae" },
        { id: "p9", name: "Capital Gate Brokers", role: "broker", kycStatus: "verified", email: "info@cgb.ae" },
      ],
      steps: [
        { id: "s9", title: "KYC/AML Verification", titleAr: "التحقق من الهوية ومكافحة غسيل الأموال", status: "done", requiredDocs: ["kyc_doc", "passport"], notes: ["Corporate KYC for Tech Invest LLC completed"], order: 1, completedAt: "2025-02-05T10:00:00Z" },
        { id: "s10", title: "Title Deed Verification", titleAr: "التحقق من سند الملكية", status: "done", requiredDocs: ["title_deed"], notes: ["Verified with Abu Dhabi municipality"], order: 2, completedAt: "2025-02-07T11:00:00Z" },
        { id: "s11", title: "NOC Collection", titleAr: "جمع شهادات عدم الممانعة", status: "done", requiredDocs: ["noc"], notes: ["NOC received from Aldar"], order: 3, completedAt: "2025-02-10T14:00:00Z" },
        { id: "s12", title: "Property Valuation", titleAr: "تقييم العقار", status: "done", requiredDocs: ["valuation_report"], notes: ["Valued at AED 520,000 — above listing"], order: 4, completedAt: "2025-02-12T09:00:00Z" },
        { id: "s13", title: "Escrow Setup", titleAr: "إعداد حساب الضمان", status: "done", requiredDocs: ["escrow_agreement"], notes: ["Escrow account with ADCB set up"], order: 5, completedAt: "2025-02-14T16:00:00Z" },
        { id: "s14", title: "Settlement", titleAr: "التسوية", status: "in_progress", requiredDocs: ["spa"], notes: ["Final review of SPA by both parties"], order: 6 },
        { id: "s15", title: "Token/Share Issuance", titleAr: "إصدار الحصص/الرموز", status: "todo", requiredDocs: [], notes: [], order: 7 },
        { id: "s16", title: "Post-Close Automation", titleAr: "أتمتة ما بعد الإغلاق", status: "todo", requiredDocs: [], notes: [], order: 8 },
      ],
      docs: [
        { id: "d5", type: "title_deed", filename: "reem_island_title.pdf", uploadedAt: "2025-02-03T09:00:00Z", extractedFields: { property_id: "RI-C14-GF", owner: "Fatima Al Nahyan", area_sqft: "3,400", plot_no: "RI-C14" }, verificationStatus: "verified", uploadedBy: "Fatima Al Nahyan" },
        { id: "d6", type: "noc", filename: "aldar_noc.pdf", uploadedAt: "2025-02-10T14:00:00Z", extractedFields: { developer: "Aldar Properties", property: "RI-C14-GF", status: "No Objection", valid_until: "2025-08-10" }, verificationStatus: "verified", uploadedBy: "Capital Gate Brokers" },
        { id: "d7", type: "valuation_report", filename: "reem_valuation_report.pdf", uploadedAt: "2025-02-12T09:00:00Z", extractedFields: { valuer: "CBRE UAE", value_aed: "520,000", method: "Comparable Sales", date: "2025-02-11" }, verificationStatus: "verified", uploadedBy: "CBRE UAE" },
        { id: "d8", type: "escrow_agreement", filename: "adcb_escrow_agreement.pdf", uploadedAt: "2025-02-14T16:00:00Z", extractedFields: { bank: "ADCB", account: "ESC-2025-4412", amount: "500,000 AED", release_conditions: "SPA signed + DLD transfer" }, verificationStatus: "verified", uploadedBy: "Emirates Escrow Services" },
      ],
      audit: [
        { ts: "2025-02-01T08:00:00Z", actor: "System", action: "Deal Created", detail: "Al Reem Island tokenized deal initiated", emoji: "🏢" },
        { ts: "2025-02-05T10:00:00Z", actor: "DeedFlow AI", action: "KYC Completed", detail: "All parties verified — mashallah!", emoji: "✅" },
        { ts: "2025-02-10T14:00:00Z", actor: "Aldar Properties", action: "NOC Issued", detail: "Developer cleared the deal — faster than a Bugatti on Sheikh Zayed Road", emoji: "🦅" },
        { ts: "2025-02-12T09:00:00Z", actor: "CBRE UAE", action: "Valuation Done", detail: "Property valued 4% above listing — someone's having a good day!", emoji: "💰" },
        { ts: "2025-02-14T16:00:00Z", actor: "ADCB", action: "Escrow Active", detail: "Funds secured — safer than gold in the souq", emoji: "🔐" },
      ],
      fieldReports: [
        { ts: "2025-02-08T09:00:00Z", user: "Capital Gate Brokers", note: "Commercial unit has strong tenant demand. Three LOIs received already.", mood: "positive", lang: "en" },
      ],
      metrics: { complianceScore: 92, riskScore: 12, estTimeToCloseDays: 5 },
    },
    {
      id: "deal-003",
      name: "JBR Beachfront Penthouse",
      nameAr: "بنتهاوس شاطئ جي بي آر",
      city: "Dubai",
      propertyType: "residential",
      tokenizationMode: "fractional",
      totalShares: 50,
      sharePrice: 100000,
      currency: "AED",
      totalValue: 5000000,
      propertyAddress: "JBR Walk, Rimal Tower, Penthouse 1",
      propertyAddressAr: "ممشى جي بي آر، برج ريمال، بنتهاوس 1",
      status: "draft",
      createdAt: "2025-02-10T12:00:00Z",
      parties: [
        { id: "p10", name: "Mohammed Al Rashid", role: "seller", sharePercent: 100, kycStatus: "verified", email: "mo@example.ae" },
        { id: "p11", name: "Luxury Investments Fund", role: "buyer", sharePercent: 40, kycStatus: "pending", email: "lif@example.com" },
      ],
      steps: [
        { id: "s17", title: "KYC/AML Verification", titleAr: "التحقق من الهوية ومكافحة غسيل الأموال", status: "in_progress", requiredDocs: ["kyc_doc", "passport"], notes: ["Waiting for fund's corporate KYC docs"], order: 1 },
        { id: "s18", title: "Title Deed Verification", titleAr: "التحقق من سند الملكية", status: "todo", requiredDocs: ["title_deed"], notes: [], order: 2 },
        { id: "s19", title: "NOC Collection", titleAr: "جمع شهادات عدم الممانعة", status: "todo", requiredDocs: ["noc"], notes: [], order: 3 },
        { id: "s20", title: "Property Valuation", titleAr: "تقييم العقار", status: "todo", requiredDocs: ["valuation_report"], notes: [], order: 4 },
        { id: "s21", title: "Escrow Setup", titleAr: "إعداد حساب الضمان", status: "todo", requiredDocs: ["escrow_agreement"], notes: [], order: 5 },
        { id: "s22", title: "Settlement", titleAr: "التسوية", status: "todo", requiredDocs: ["spa"], notes: [], order: 6 },
        { id: "s23", title: "Token/Share Issuance", titleAr: "إصدار الحصص/الرموز", status: "todo", requiredDocs: [], notes: [], order: 7 },
        { id: "s24", title: "Post-Close Automation", titleAr: "أتمتة ما بعد الإغلاق", status: "todo", requiredDocs: [], notes: [], order: 8 },
      ],
      docs: [],
      audit: [
        { ts: "2025-02-10T12:00:00Z", actor: "System", action: "Deal Created", detail: "JBR Penthouse deal drafted — living the high life!", emoji: "🏡" },
      ],
      fieldReports: [],
      metrics: { complianceScore: 15, riskScore: 45, estTimeToCloseDays: 30 },
    },
    {
      id: "deal-004",
      name: "Saadiyat Island Villa Compound",
      nameAr: "مجمع فلل جزيرة السعديات",
      city: "Abu Dhabi",
      propertyType: "residential",
      tokenizationMode: "tokenized",
      totalShares: 200,
      sharePrice: 25000,
      currency: "AED",
      totalValue: 5000000,
      propertyAddress: "Saadiyat Island, District 4, Villa 17",
      propertyAddressAr: "جزيرة السعديات، المنطقة 4، فيلا 17",
      status: "completed",
      createdAt: "2024-11-01T08:00:00Z",
      parties: [
        { id: "p12", name: "Noura Al Ketbi", role: "seller", sharePercent: 0, kycStatus: "verified", email: "noura@example.ae" },
        { id: "p13", name: "Gulf Ventures Ltd", role: "buyer", sharePercent: 55, kycStatus: "verified", email: "gv@example.ae" },
        { id: "p14", name: "Ali Bin Saeed", role: "buyer", sharePercent: 45, kycStatus: "verified", email: "ali@example.ae" },
      ],
      steps: [
        { id: "s25", title: "KYC/AML Verification", titleAr: "التحقق من الهوية", status: "done", requiredDocs: ["kyc_doc"], notes: [], order: 1, completedAt: "2024-11-05T10:00:00Z" },
        { id: "s26", title: "Title Deed Verification", titleAr: "التحقق من سند الملكية", status: "done", requiredDocs: ["title_deed"], notes: [], order: 2, completedAt: "2024-11-08T10:00:00Z" },
        { id: "s27", title: "NOC Collection", titleAr: "جمع شهادات عدم الممانعة", status: "done", requiredDocs: ["noc"], notes: [], order: 3, completedAt: "2024-11-12T10:00:00Z" },
        { id: "s28", title: "Property Valuation", titleAr: "تقييم العقار", status: "done", requiredDocs: ["valuation_report"], notes: [], order: 4, completedAt: "2024-11-15T10:00:00Z" },
        { id: "s29", title: "Escrow Setup", titleAr: "إعداد حساب الضمان", status: "done", requiredDocs: ["escrow_agreement"], notes: [], order: 5, completedAt: "2024-11-18T10:00:00Z" },
        { id: "s30", title: "Settlement", titleAr: "التسوية", status: "done", requiredDocs: ["spa"], notes: [], order: 6, completedAt: "2024-11-22T10:00:00Z" },
        { id: "s31", title: "Token/Share Issuance", titleAr: "إصدار الرموز", status: "done", requiredDocs: [], notes: ["200 tokens issued on-chain"], order: 7, completedAt: "2024-11-23T10:00:00Z" },
        { id: "s32", title: "Post-Close Automation", titleAr: "أتمتة ما بعد الإغلاق", status: "done", requiredDocs: [], notes: ["Rent distribution active"], order: 8, completedAt: "2024-11-25T10:00:00Z" },
      ],
      docs: [
        { id: "d9", type: "title_deed", filename: "saadiyat_villa_title.pdf", uploadedAt: "2024-11-03T09:00:00Z", extractedFields: { property_id: "SI-D4-V17", owner: "Noura Al Ketbi", area_sqft: "5,200" }, verificationStatus: "verified", uploadedBy: "Noura Al Ketbi" },
      ],
      audit: [
        { ts: "2024-11-01T08:00:00Z", actor: "System", action: "Deal Created", detail: "Saadiyat Villa deal initiated", emoji: "🏡" },
        { ts: "2024-11-25T10:00:00Z", actor: "DeedFlow AI", action: "Deal Completed", detail: "All steps done — mabrouk! 🎉", emoji: "🎉" },
      ],
      fieldReports: [],
      metrics: { complianceScore: 100, riskScore: 0, estTimeToCloseDays: 0 },
    },
  ];
}

export const mockLeaderboard: LeaderboardEntry[] = [
  { name: "Dubai Land Department", avatar: "🏛️", reviews: 847, avgDays: 2.1 },
  { name: "Emaar NOC Team", avatar: "🏗️", reviews: 612, avgDays: 3.4 },
  { name: "ADCB Escrow Ops", avatar: "🏦", reviews: 534, avgDays: 1.8 },
  { name: "CBRE Valuations", avatar: "📊", reviews: 421, avgDays: 4.2 },
  { name: "RERA Compliance", avatar: "⚖️", reviews: 389, avgDays: 5.1 },
];
